# Generated by Django 5.0.6 on 2024-06-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_bid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
